version: '3'

services:
  ampache:
    build: .
    #image: ampache/ampache:latest
    image: ampache
    container_name: ampache
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/config:/var/www/config
      - ./data/log:/var/log/ampache
      - ./data/media:/media
      - ./data/mysql:/var/lib/mysql
    environment:
      - ORG_PARAMS=/C=CO/ST=ST/L=LO/OU=OU/O=Company, Inc./CN=mydomain.com